# Copyright 2024 Roi Martin

name: Lint
on: [push, pull_request]
permissions:
  contents: read
jobs:
  golangci-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v1.59.1
      GOLANGCI_LINT_OUT_FORMAT: ${{ github.event_name == 'pull_request' && 'github-actions' || 'colored-line-number' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Remove Go problem matchers
        run: echo "::remove-matcher owner=go::"
      - name: Install "golangci-lint"
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Run "golangci-lint run"
        run: golangci-lint run --out-format=${{ env.GOLANGCI_LINT_OUT_FORMAT }} ./...
